/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahoahtml;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static mahoahtml.Mahoahtml.data;
import static mahoahtml.Mahoahtml.dich_trai_bit;
import static mahoahtml.Mahoahtml.docMessage;
import static mahoahtml.Mahoahtml.encodeBin;
import static mahoahtml.Mahoahtml.laythuoctinhtrongthe;
import static mahoahtml.Mahoahtml.loaibokhoangtrang;
import static mahoahtml.Mahoahtml.loccacthekhongcothuoctinh;
import static mahoahtml.Mahoahtml.tachcacthe;
import static mahoahtml.Steg.bit;
import static mahoahtml.Steg.shiftString;

public class Ma_hoa_html extends javax.swing.JFrame {

    public Ma_hoa_html() {
        initComponents();
        setLocation(200, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        messageMh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonmh = new javax.swing.JButton();
        pathname = new javax.swing.JLabel();
        open_file = new javax.swing.JButton();
        save_file = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nhap_key = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonkiemtracapthuoctinh = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        open_file2 = new javax.swing.JButton();
        pathname3 = new javax.swing.JLabel();
        buttonmh2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        open_file1 = new javax.swing.JButton();
        pathname2 = new javax.swing.JLabel();
        buttonmh1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nhap_key1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        messageKp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonkp = new javax.swing.JButton();
        pathname1 = new javax.swing.JLabel();
        open_filekp = new javax.swing.JButton();
        save_filekp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreakp = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttoncleankp = new javax.swing.JButton();
        nhapkeykp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageMh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageMhActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập vào message bạn cần mã hóa");

        buttonmh.setText("Mã hóa dữ liệu");
        buttonmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmhActionPerformed(evt);
            }
        });

        open_file.setText("open file html...");
        open_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_fileActionPerformed(evt);
            }
        });

        save_file.setText("save file ");
        save_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_fileActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel6.setText("Nhóm 3 - D16CQAT01_N");

        jButton1.setText("Clean");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nhap_key.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhap_keyMouseClicked(evt);
            }
        });
        nhap_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_keyActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/key.png"))); // NOI18N
        jLabel10.setText("Nhập key");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/tải xuống (1).png"))); // NOI18N

        jButtonkiemtracapthuoctinh.setText("Kiểm tra cặp thuộc tính");
        jButtonkiemtracapthuoctinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkiemtracapthuoctinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_file, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathname, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(open_file)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonkiemtracapthuoctinh)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhap_key, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageMh)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(buttonmh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(open_file)
                        .addComponent(jButtonkiemtracapthuoctinh)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nhap_key)
                        .addComponent(messageMh, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                    .addComponent(pathname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonmh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_file))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jButton1)))
                        .addGap(67, 67, 67))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Mã hóa dữ liệu", new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/encoding.png")), jPanel3); // NOI18N

        open_file2.setText("Open file html...");
        open_file2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_file2ActionPerformed(evt);
            }
        });

        buttonmh2.setText("Phát hiện giấu tin");
        buttonmh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmh2ActionPerformed(evt);
            }
        });

        jLabel14.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel15.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel16.setText("Nhóm 3 - D16CQAT01_N");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonmh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pathname3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(open_file2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(open_file2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathname3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(buttonmh2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Phát hiện giấu tin", new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/Lock-Unlock-icon (1).png")), jPanel6); // NOI18N

        open_file1.setText("Open file html...");
        open_file1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_file1ActionPerformed(evt);
            }
        });

        buttonmh1.setText("Phát hiện giấu tin và giải mã");
        buttonmh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmh1ActionPerformed(evt);
            }
        });

        jLabel7.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel8.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel9.setText("Nhóm 3 - D16CQAT01_N");

        nhap_key1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhap_key1MouseClicked(evt);
            }
        });
        nhap_key1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_key1ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/key.png"))); // NOI18N
        jLabel13.setText("Nhập key");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonmh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(open_file1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pathname2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhap_key1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(open_file1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathname2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nhap_key1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(buttonmh1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab(" Giải mã", new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/Lock-Unlock-icon (1).png")), jPanel4); // NOI18N

        messageKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageKpActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập vào message đã giải mã");

        buttonkp.setText("Khôi phục file ban đầu");
        buttonkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkpActionPerformed(evt);
            }
        });

        open_filekp.setText("open file html...");
        open_filekp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_filekpActionPerformed(evt);
            }
        });

        save_filekp.setText("save file ");
        save_filekp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_filekpActionPerformed(evt);
            }
        });

        jTextAreakp.setColumns(20);
        jTextAreakp.setRows(5);
        jScrollPane2.setViewportView(jTextAreakp);

        jLabel3.setText("TOOL MÃ HÓA VÀ GIẢI MÃ FILE HTML");

        jLabel4.setText("Nhóm 3 - D16CQAT01_N");

        buttoncleankp.setText("Clean");
        buttoncleankp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncleankpActionPerformed(evt);
            }
        });

        nhapkeykp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhapkeykpMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/key.png"))); // NOI18N
        jLabel11.setText("Nhập key");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(open_filekp)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(save_filekp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(pathname1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nhapkeykp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageKp)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(buttonkp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(buttoncleankp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_filekp)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhapkeykp)
                    .addComponent(pathname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageKp, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonkp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_filekp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(buttoncleankp)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Khôi phục lại file html ban đầu", new javax.swing.ImageIcon(getClass().getResource("/mahoahtml/icon/restore.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
File f;

    private static String readFile(File file) {
        String s1 = "";
        try {
            //taFile.setText("");
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            //String line ;
            String line = "";
            String s = "";
            while ((line = br.readLine()) != null) {
                //taFile.append(line +"\n");
                s += line;

            }
            s1 = s1 + s;
            br.close();
            fr.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "bạn chưa nhập file html nào");
        }
        return s1;
    }

    public static ArrayList<String> laythuoctinhtrongthe(String a) {
        ArrayList<String> b = new ArrayList<String>();

        //   Pattern tagPattern = Pattern.compile("([mangThe-zA-Z]+)(=['|\"]([mangThe-zA-Z0-9#]+)?['|\"|\\.])");
        Pattern tagPattern = Pattern.compile("([a-zA-Z]+)(=['|\"]([a-zA-Z0-9#\\.]+)?['|\"])");
        Matcher m = tagPattern.matcher(a);
        while (m.find()) {
            b.add(m.group());

        }
        return b;

    }

    public static StringBuilder encodeBin(String s) {
        byte[] bytes = s.getBytes();
        StringBuilder binary = new StringBuilder();
        for (byte b : bytes) {
            int val = b;
            for (int i = 0; i < 8; i++) {
                binary.append((val & 128) == 0 ? 0 : 1);
                val <<= 1;
            }
            binary.append(' ');
        }
        return binary;
    }
     public static ArrayList<String> laycapthuoctinhtrongthe(String a)
    {
        ArrayList <String> arrcapthuoctinh= new ArrayList<String>();
            
            //Pattern tagPattern = Pattern.compile("([mangThe-zA-Z]+)(=['|\"]([mangThe-zA-Z0-9#]+)?['|\"|\\.])");
         // Pattern tagPattern = Pattern.compile("([mangThe-zA-Z]+)(=['|\"]([mangThe-zA-Z0-9#\\.]+)?['|\"])");
         Pattern tagPattern = Pattern.compile("([a-zA-Z]+)(=['|\"]([a-zA-Z0-9#\\.]+)?['|\"])(\\s[a-zA-Z]+)(=['|\"]([a-zA-Z|a-zA-Z0-9#\\.]+)?['|\"])?");
     
                    Matcher m = tagPattern.matcher(a);
                    
                    
                    while(m.find())
                    {
                        arrcapthuoctinh.add(m.group());
                        
                    }
                    return arrcapthuoctinh;
                    
    }
public static ArrayList<String> layCacTheCoHaiThuocTinh(ArrayList<String>a)
    {
        ArrayList<String>mangHaiThuocTinh= new ArrayList<>();
        for(int i=0;i<a.size();i++)
         {
             mangHaiThuocTinh=laycapthuoctinhtrongthe(a.get(i));
           //System.out.println(mangHaiThuocTinh+"mang 2 thuoc tinh");
        if(mangHaiThuocTinh.isEmpty())
           {
               a.remove(i);
               i--;
           }
        
         }
        return a;
    }

    private void messageMhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageMhActionPerformed
        if (!messageMh.getText().equals("")) {

        }
    }//GEN-LAST:event_messageMhActionPerformed

    private void buttonmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmhActionPerformed

        try {
            String key1 = nhap_key.getText();

            Character key = key1.charAt(0);
            int sobitdich = 0;
            int ascii = (int) key;
            System.out.println(ascii);

            if (ascii > 64 && ascii < 69 || ascii > 96 && ascii < 101) {
                sobitdich = 1;
            } else if (ascii > 68 && ascii < 73 || ascii > 100 && ascii < 105) {
                sobitdich = 2;
            } else if (ascii > 72 && ascii < 77 || ascii > 104 && ascii < 109) {
                sobitdich = 3;
            } else if (ascii > 76 && ascii < 81 || ascii > 108 && ascii < 113) {
                sobitdich = 4;
            } else if (ascii > 80 && ascii < 85 || ascii > 112 && ascii < 117) {
                sobitdich = 5;
            } else if (ascii > 84 && ascii < 88 || ascii > 116 && ascii < 120) {
                sobitdich = 6;
            } else if (ascii > 87 && ascii < 91 || ascii > 119 && ascii < 123) {
                sobitdich = 7;
            }
            String chuoiTuFile = readFile(f);

            StringBuilder messageMahoa = encodeBin(messageMh.getText());

            String chuoinhiphan = messageMahoa.toString();
            String[] mangnhiphan = chuoinhiphan.split(" ");
            String chuoidadich = "";
            for (int i = 0; i < mangnhiphan.length; i++) {
                mangnhiphan[i] = dich_trai_bit(mangnhiphan[i], sobitdich);

            }
            for (int i = 0; i < mangnhiphan.length; i++) {
                chuoidadich += " " + mangnhiphan[i];
            }

            String chuoiDaDichLoaiKhoangTrang = loaibokhoangtrang(chuoidadich);

            System.out.println(chuoiDaDichLoaiKhoangTrang);
            String[] mangDaDichLoaiKhoangTrang = chuoiDaDichLoaiKhoangTrang.split("");
            int[] Binary = new int[mangDaDichLoaiKhoangTrang.length];
            for (int i = 0; i < mangDaDichLoaiKhoangTrang.length; i++) {
                Binary[i] = Integer.parseInt(mangDaDichLoaiKhoangTrang[i]);
            }
            // int []Binary={0,0,1,1,1,1,1,1};
            ArrayList<String> mangThe = new ArrayList<>();
            mangThe = tachcacthe(chuoiTuFile);

            mangThe = loccacthekhongcothuoctinh(mangThe);
            mangThe=layCacTheCoHaiThuocTinh(mangThe);
            ArrayList<String> mangHaiThuocTinhSwap = new ArrayList<>();
            ArrayList<String> mangHaiThuocTinhGiuNguyen = new ArrayList<>();
            ArrayList<String> thedadoi = new ArrayList<>();
            for (int i = 0; i < Binary.length; i++) {
                //System.out.println(mangThe.get(i)+"the chua doi");
                mangHaiThuocTinhSwap = laythuoctinhtrongthe(mangThe.get(i));
                mangHaiThuocTinhGiuNguyen = laythuoctinhtrongthe(mangThe.get(i));

                if (Binary[i] == 0) {
                    System.out.println(Binary[i]);
                    Collections.swap(mangHaiThuocTinhSwap, 0, 1);
                }
                String a0 = mangThe.get(i).replace(mangHaiThuocTinhGiuNguyen.get(0), "tam");
                String a1 = a0.replace(mangHaiThuocTinhGiuNguyen.get(1), mangHaiThuocTinhSwap.get(1));
                String a2 = a1.replace("tam", mangHaiThuocTinhSwap.get(0));
                // System.out.println(a2+"//");
                thedadoi.add(a2);
                // for(String temp: mangHaiThuocTinhSwap){
                // System.out.println(temp);

                // }
                //    for(String temp2: mangHaiThuocTinhGiuNguyen){
                //System.out.println(temp2);
                //       }
            }
            // for(String temp3: thedadoi){
            //System.out.println(temp3);
            //     }
            // for(String temp4:mangThe)
            // {
            //     System.out.println(temp4+"thechuadoi"); 
            //     }
            ArrayList<String> listtext = new ArrayList<>();
            listtext = data(chuoiTuFile);
            // System.out.println(chuoiTuFile);
            for (int i = 0; i < thedadoi.size(); i++) {
                chuoiTuFile = chuoiTuFile.replace(mangThe.get(i), thedadoi.get(i));
            }

            System.out.println("String da ma hoa" + chuoiTuFile);
            jTextArea1.append(chuoiTuFile);
            JOptionPane.showMessageDialog(rootPane, "Mã hóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Mã hóa thất bại, vui lòng nhập file html lưu được số kí tự nhiều hơn");
        }


    }//GEN-LAST:event_buttonmhActionPerformed

    private void open_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_fileActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            pathname.setText(filename);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn file html ");
        }


    }//GEN-LAST:event_open_fileActionPerformed

    private void save_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        File f1 = fc.getSelectedFile();

        try {
            FileWriter fw = new FileWriter(f1);
            String text = jTextArea1.getText();
            fw.write(text);
            fw.close();
            jTextArea1.setText(null);
            JOptionPane.showMessageDialog(rootPane, "Lưu file mã hóa thành công");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Lưu file mã hóa thất bại");
        }
    }//GEN-LAST:event_save_fileActionPerformed

    private void messageKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageKpActionPerformed
        // TODO add your handling code here:
        if (!messageKp.getText().equals("")) {

        }
    }//GEN-LAST:event_messageKpActionPerformed

    private void buttonkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkpActionPerformed
        // TODO add your handling code here:
        try {

            String keykp = nhapkeykp.getText();
            Character key = keykp.charAt(0);
            int sobitdich = 0;
            int ascii = (int) key;
            System.out.println(ascii);

            if (ascii > 64 && ascii < 69 || ascii > 96 && ascii < 101) {
                sobitdich = 1;
            } else if (ascii > 68 && ascii < 73 || ascii > 100 && ascii < 105) {
                sobitdich = 2;
            } else if (ascii > 72 && ascii < 77 || ascii > 104 && ascii < 109) {
                sobitdich = 3;
            } else if (ascii > 76 && ascii < 81 || ascii > 108 && ascii < 113) {
                sobitdich = 4;
            } else if (ascii > 80 && ascii < 85 || ascii > 112 && ascii < 117) {
                sobitdich = 5;
            } else if (ascii > 84 && ascii < 88 || ascii > 116 && ascii < 120) {
                sobitdich = 6;
            } else if (ascii > 87 && ascii < 91 || ascii > 119 && ascii < 123) {
                sobitdich = 7;
            }
            String chuoiTuFile = readFile(f);

            StringBuilder messageGiaiMa = encodeBin(messageKp.getText());

            String chuoinhiphan = messageGiaiMa.toString();
            String[] mangnhiphan = chuoinhiphan.split(" ");
            String chuoidadich = "";
            for (int i = 0; i < mangnhiphan.length; i++) {
                mangnhiphan[i] = dich_trai_bit(mangnhiphan[i], sobitdich);

            }
            for (int i = 0; i < mangnhiphan.length; i++) {
                chuoidadich += " " + mangnhiphan[i];
            }

            String m3 = loaibokhoangtrang(chuoidadich);

            System.out.println(m3);
            String[] M3 = m3.split("");
            int[] Binary = new int[M3.length];
            for (int i = 0; i < M3.length; i++) {
                Binary[i] = Integer.parseInt(M3[i]);
            }
            // int []Binary={0,0,1,1,1,1,1,1};
            ArrayList<String> mangThe = new ArrayList<>();
            mangThe = tachcacthe(chuoiTuFile);

            mangThe = loccacthekhongcothuoctinh(mangThe);
            mangThe = layCacTheCoHaiThuocTinh(mangThe);
            ArrayList<String> b = new ArrayList<>();
            ArrayList<String> c = new ArrayList<>();
            ArrayList<String> thedadoi = new ArrayList<>();
            for (int i = 0; i < Binary.length; i++) {
                //System.out.println(mangThe.get(i)+"the chua doi");
                b = laythuoctinhtrongthe(mangThe.get(i));
                c = laythuoctinhtrongthe(mangThe.get(i));

                if (Binary[i] == 0) {
                    System.out.println(Binary[i]);
                    Collections.swap(b, 0, 1);
                }
                String a0 = mangThe.get(i).replace(c.get(0), "tam");
                String a1 = a0.replace(c.get(1), b.get(1));
                String a2 = a1.replace("tam", b.get(0));
                // System.out.println(a2+"//");
                thedadoi.add(a2);
                // for(String temp: mangHaiThuocTinhSwap){
                // System.out.println(temp);

                // }
                //    for(String temp2: mangHaiThuocTinhGiuNguyen){
                //System.out.println(temp2);
                //       }
            }
            // for(String temp3: thedadoi){
            //System.out.println(temp3);
            //     }
            // for(String temp4:mangThe)
            // {
            //     System.out.println(temp4+"thechuadoi"); 
            //     }
            ArrayList<String> listtext = new ArrayList<>();
            listtext = data(chuoiTuFile);
            // System.out.println(chuoiTuFile);
            for (int i = 0; i < thedadoi.size(); i++) {
                chuoiTuFile = chuoiTuFile.replace(mangThe.get(i), thedadoi.get(i));
            }

            System.out.println("String da ma hoa" + chuoiTuFile);
            jTextAreakp.append(chuoiTuFile);
            JOptionPane.showMessageDialog(rootPane, "Khôi phục thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Khôi phục thất bại, vui lòng nhập lại file html ");
        }
    }//GEN-LAST:event_buttonkpActionPerformed

    private void open_filekpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_filekpActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            pathname1.setText(filename);
        } catch (Exception e) {
            // JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn file html ");
        }
    }//GEN-LAST:event_open_filekpActionPerformed

    private void save_filekpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_filekpActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        File f1 = fc.getSelectedFile();

        try {
            FileWriter fw = new FileWriter(f1);
            String text = jTextAreakp.getText();
            fw.write(text);
            fw.close();
            jTextAreakp.setText("");
            JOptionPane.showMessageDialog(rootPane, "Lưu file khôi phục thành công");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, "Lưu file khôi phục thất bại");
        }
    }//GEN-LAST:event_save_filekpActionPerformed

    private void open_file1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_file1ActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            pathname2.setText(filename);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn file html ");
        }

    }//GEN-LAST:event_open_file1ActionPerformed
    public static Map tagHTML(Map<String, String> m) {
        //m.put("type", "value");
        //m.put("width", "height");
        //m.put("charset", "content");
        m.put("href", "rel");
        m.put("src", "alt");
        m.put("class", "id");

        return m;
    }

    public static String decodetoASCII(String s, int bitsh) {
        String s2 = "";
        char nextChar;
        for (int i = 0; i <= s.length() - 7; i += 8) {
            String shift = shiftString(s.substring(i, i + 8), bitsh, true);
            System.out.println("chuoi ky tu dau shift: " + shift);
            nextChar = (char) Integer.parseInt(shift, 2);
            s2 += nextChar;
        }
        return s2;
    }

    public static ArrayList<String> laythuoctinhtrongthegiaima(ArrayList<String> a) {
        for (int i = 0; i < a.size(); i++) {
            Pattern tagPattern = Pattern.compile("[a-zA-Z]+=");
            Matcher m = tagPattern.matcher(a.get(i));
            String attr = "";
            while (m.find()) {
                attr += m.group() + " ";// style= value=
            }
            a.set(i, attr.replaceAll("= ", " "));
        }
        return a;
    }

    public static String shiftString(String s, int i, boolean kt) {
        // true is right shift
        // false is left shift
        if (kt == true) {
            for (int j = 0; j < i; j++) {
                s = s.substring(s.length() - 1) + s.substring(0, s.length() - 1);
            }
        } else if (kt == false) {
            for (int j = 0; j < i; j++) {
                s = s.substring(1, s.length()) + s.substring(0, 1);
            }
        }
        return s;
    }

    public static int bit(String keykp) {
        Character key = keykp.charAt(0);
        int sobitdich = 0;
        int ascii = (int) key;
        System.out.println("ascii ky tu dau cua key: " + ascii);
        if (ascii > 64 && ascii < 69 || ascii > 96 && ascii < 101) {
            sobitdich = 1;
        } else if (ascii > 68 && ascii < 73 || ascii > 100 && ascii < 105) {
            sobitdich = 2;
        } else if (ascii > 72 && ascii < 77 || ascii > 104 && ascii < 109) {
            sobitdich = 3;
        } else if (ascii > 76 && ascii < 81 || ascii > 108 && ascii < 113) {
            sobitdich = 4;
        } else if (ascii > 80 && ascii < 85 || ascii > 112 && ascii < 117) {
            sobitdich = 5;
        } else if (ascii > 84 && ascii < 88 || ascii > 116 && ascii < 120) {
            sobitdich = 6;
        } else if (ascii > 87 && ascii < 91 || ascii > 119 && ascii < 123) {
            sobitdich = 7;
        }
        return sobitdich;
    }
    public static String filterASCII(String s)
    {
        String txt="";
        for(int i=0; i<s.length(); i++)
        {
            char p=s.charAt(i);
            int asciiVal = (int)p;
            System.out.println("val: " +asciiVal);
            if(asciiVal >= 32 && asciiVal <=126)
            {
                txt+=p;
            }
        }
        return txt;
    }
    private void buttonmh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmh1ActionPerformed
        // TODO add your handling code here:
        try {

            String keyy = nhap_key1.getText();

            String s = readFile(f);

            ArrayList<String> a = new ArrayList<>();
            a = tachcacthe(s);
            a = loccacthekhongcothuoctinh(a);
            a = laythuoctinhtrongthegiaima(a);
            Map<String, String> m = new HashMap<>();
            m = tagHTML(m); // type value =1 width heigh =1
            String encode = "";
            for (int i = 0; i < a.size(); i++) {
                String[] mattr = a.get(i).split(" ");
                for (int j = 0; j < mattr.length - 1; j++) {
                    if (m.containsKey(mattr[j]) && (m.containsValue(mattr[j + 1]))) {
                        encode += "1";
                        j++;
                    } else if (m.containsKey(mattr[j + 1]) && (m.containsValue(mattr[j]))) {
                        encode += "0";
                        j++;
                    }

                }
            }
            int bitsh = bit(keyy);
            //JOptionPane.showMessageDialog(rootPane, encode);
            JOptionPane.showMessageDialog(rootPane, filterASCII(decodetoASCII(encode, bitsh)));
            jTextArea1.append(s);
            //JOptionPane.showMessageDialog(rootPane, "Giải mã thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR");
        }
    }//GEN-LAST:event_buttonmh1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttoncleankpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncleankpActionPerformed
        // TODO add your handling code here:\\
        jTextAreakp.setText("");
    }//GEN-LAST:event_buttoncleankpActionPerformed

    private void nhapkeykpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhapkeykpMouseClicked
        // TODO add your handling code here:
        nhapkeykp.setText("");
    }//GEN-LAST:event_nhapkeykpMouseClicked

    private void nhap_keyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhap_keyMouseClicked
        // TODO add your handling code here:
        nhap_key.setText("");
    }//GEN-LAST:event_nhap_keyMouseClicked

    private void nhap_key1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhap_key1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nhap_key1MouseClicked

    private void nhap_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhap_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhap_keyActionPerformed

    private void open_file2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_file2ActionPerformed
        // TODO add your handling code here:
          try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            pathname3.setText(filename);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn file html ");
        }
        
    }//GEN-LAST:event_open_file2ActionPerformed
    public static String decodetoASCIIphathien(String s) {
        String s2 = "";
        char nextChar;
        for (int i = 0; i <= s.length() - 7; i += 8) {
            nextChar = (char) Integer.parseInt(s.substring(i, i + 8), 2);
            s2 += nextChar;
        }
        return s2;
    }
    private void buttonmh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmh2ActionPerformed
        // TODO add your handling code here:
        
         try {

            String s = readFile(f);

            ArrayList<String> a = new ArrayList<>();
            a = tachcacthe(s);
            a = loccacthekhongcothuoctinh(a);
            //System.out.println(mangThe);
            a = laythuoctinhtrongthegiaima(a);
            Map<String, String> m = new HashMap<>();
            m = tagHTML(m); // type value =1 width heigh =1
            String encode = "";
            //String notfound = "11111111";
            for (int i = 0; i < a.size(); i++) {
                String[] mattr = a.get(i).split(" ");
                for (int j = 0; j < mattr.length - 1; j++) {
                    if (m.containsKey(mattr[j]) && (m.containsValue(mattr[j + 1]))) {
                        encode += "1";
                        j++;
                    } else if (m.containsKey(mattr[j + 1]) && (m.containsValue(mattr[j]))) {
                        encode += "0";
                        j++;
                    }

                }
            }
            if (decodetoASCIIphathien(encode).equals("")) {
                JOptionPane.showMessageDialog(null, "File html không có giấu tin !!! ");
            } else {
                JOptionPane.showMessageDialog(null, "File html có giấu tin !!!");
            }

            jTextArea1.append(s);
            JOptionPane.showMessageDialog(rootPane, "Chuyển sang bước kế tiếp");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERROR");
        }
    }//GEN-LAST:event_buttonmh2ActionPerformed

    private void nhap_key1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhap_key1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhap_key1ActionPerformed

    private void jButtonkiemtracapthuoctinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkiemtracapthuoctinhActionPerformed
        // TODO add your handling code here:
       
        
       
        String chuoiTuFile=readFile(f);
        System.out.println(chuoiTuFile);
     
         ArrayList<String> mangThe = new ArrayList<>();
            mangThe = tachcacthe(chuoiTuFile);

            mangThe = loccacthekhongcothuoctinh(mangThe);
            mangThe = layCacTheCoHaiThuocTinh(mangThe);
              String a="";
        ArrayList<String>mangthuoctinh= new ArrayList<>();
         for(int i=0;i<mangThe.size();i++)
        {
           System.out.println(mangThe.get(i));
        }
         for(int i=0;i<mangThe.size();i++)
        {
            mangthuoctinh=laycapthuoctinhtrongthe(mangThe.get(i));
            
         
         
           for(String temp:mangthuoctinh)
       {
             System.out.println(temp);
             a+="_"+temp;
          }
         
            
        }
         String phantuloi="";
         String phantuloi2="";
         System.out.println(a);
         String []mangcapthuoctinh=a.split("_");
         for(int i=0;i<mangcapthuoctinh.length;i++)
         {
             System.out.println(mangcapthuoctinh[i]);
         }
          
          
           
           for(int i=0;i<mangcapthuoctinh.length;i++)
         {
             if(mangcapthuoctinh[i].startsWith("value")||mangcapthuoctinh[i].startsWith("height")||mangcapthuoctinh[i].startsWith("alt")||mangcapthuoctinh[i].startsWith("rel"))
             {
                 System.out.println("loi");
                 phantuloi+="_"+"loi";
             }
             else
             {
                 System.out.println("ko");
                 phantuloi+="_"+"ko";
             }
            
         }
           System.out.println(phantuloi);
         
           
           
        
            
            
           for(int i=0;i<mangcapthuoctinh.length;i++)
         {
             if(mangcapthuoctinh[i].endsWith("type")||mangcapthuoctinh[i].endsWith("width")||mangcapthuoctinh[i].endsWith("src")||mangcapthuoctinh[i].endsWith("href"))
             {
                 System.out.println("loi");
                 phantuloi2+="_"+"loi";
             }
             else
             {
                 System.out.println("ko");
                 phantuloi2+="_"+"ko";
             }
            
         }
            System.out.println(phantuloi2);
         
             if(phantuloi.contains("loi")||phantuloi2.contains("loi"))
             {
                 JOptionPane.showMessageDialog(rootPane,"File chứa cặp thuộc tính bị ngược");
             }
             else if(phantuloi.contains("ko")&&phantuloi2.contains("ko"))
             {
                 JOptionPane.showMessageDialog(rootPane,"File chứa cặp thuộc tính  không bị ngược");
             }
             
             
        
        
             
        
       
        
    }//GEN-LAST:event_jButtonkiemtracapthuoctinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ma_hoa_html.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ma_hoa_html.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ma_hoa_html.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ma_hoa_html.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ma_hoa_html().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncleankp;
    private javax.swing.JButton buttonkp;
    private javax.swing.JButton buttonmh;
    private javax.swing.JButton buttonmh1;
    private javax.swing.JButton buttonmh2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonkiemtracapthuoctinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreakp;
    private javax.swing.JTextField messageKp;
    private javax.swing.JTextField messageMh;
    private javax.swing.JTextField nhap_key;
    private javax.swing.JTextField nhap_key1;
    private javax.swing.JTextField nhapkeykp;
    private javax.swing.JButton open_file;
    private javax.swing.JButton open_file1;
    private javax.swing.JButton open_file2;
    private javax.swing.JButton open_filekp;
    private javax.swing.JLabel pathname;
    private javax.swing.JLabel pathname1;
    private javax.swing.JLabel pathname2;
    private javax.swing.JLabel pathname3;
    private javax.swing.JButton save_file;
    private javax.swing.JButton save_filekp;
    // End of variables declaration//GEN-END:variables
}
